### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by prsigma** [JaneJiayiDong/GROD#1]
Hi, thanks for your awesome work, could you please provide the datasets for training?

**Comment by JaneJiayiDong** [comment]
The dataset for gene regulatory network inference uses [Beeline](https://github.com/Murali-group/Beeline). Sorry, I will add relevant documentation soon.

**Comment by pengrui-code** [comment]
> The dataset for gene regulatory network inference uses [Beeline](https://github.com/Murali-group/Beeline). Sorry, I will add relevant documentation soon.

thanks!

**Comment by prsigma** [comment]
> The dataset for gene regulatory network inference uses [Beeline](https://github.com/Murali-group/Beeline). Sorry, I will add relevant documentation soon.

Hello, I'm glad to see your prompt response, but I noticed that the 'expression.csv' file you uploaded is empty. Also, could you please upload the 'tfs+500' and 'tfs+1000' datasets used in the paper? It seems that the 'Beeline' paper did not release these datasets. thanks！

**Comment by JaneJiayiDong** [comment]
Sorry, I reupload the data (mESC_tfs+500) and the complete dataset needs some time to be sorted and uploaded. And you can try to use code(generateExpInputs.py) in Beeline and raw data in https://zenodo.org/records/3701939 to generate these related datasets.

**Comment by prsigma** [comment]
> Sorry, I reupload the data (mESC_tfs+500) and the complete dataset needs some time to be sorted and uploaded. And you can try to use code(generateExpInputs.py) in Beeline and raw data in https://zenodo.org/records/3701939 to generate these related datasets.

Thank you for your response. I have reviewed the `generateExpInputs.py` code in BEELINE, and it does indeed generate the `tfs+500` and `tfs+1000` datasets. However, it requires human and mouse transcription factor (TF) databases file, and it seems these files are not included at https://zenodo.org/records/3701939. Where can I obtain these TF databases files? thanks very much!
<img width="746" alt="image" src="https://github.com/JaneJiayiDong/GROD/assets/118984300/c48453f8-ae51-42b8-b6b0-1d0e5b5ef15b">

**Comment by JaneJiayiDong** [comment]
You can download this file in https://zenodo.org/records/3701939.
![image](https://github.com/JaneJiayiDong/GROD/assets/99305486/1aac4bda-07b8-403c-80d1-1a1723f482d1)
![image](https://github.com/JaneJiayiDong/GROD/assets/99305486/141e04a7-e683-44ef-97b2-39016bb7dd3e)

**Comment by prsigma** [comment]
> You can download this file in https://zenodo.org/records/3701939. ![image](https://private-user-images.githubusercontent.com/99305486/311425752-1aac4bda-07b8-403c-80d1-1a1723f482d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzY3MTEsIm5iZiI6MTcwOTk3NjQxMSwicGF0aCI6Ii85OTMwNTQ4Ni8zMTE0MjU3NTItMWFhYzRiZGEtMDdiOC00MDNjLTgwZDEtMWExNzIzZjQ4MmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA5MjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMGE1NmYyNjA0MzhmNDZjMWUyOWJiYzNiNTAzNDFkNzk0M2ZhNTE5YjAyOGNjNzE1NGU1NmQwMzRkNjhmYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JQMoV7cXgT1Yafrcu1b9jsPgHZq8XiYkrarf2l44qns) ![image](https://private-user-images.githubusercontent.com/99305486/311425735-141e04a7-e683-44ef-97b2-39016bb7dd3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzY3MTEsIm5iZiI6MTcwOTk3NjQxMSwicGF0aCI6Ii85OTMwNTQ4Ni8zMTE0MjU3MzUtMTQxZTA0YTctZTY4My00NGVmLTk3YjItMzkwMTZiYjdkZDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA5MjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5M2I5Nzk5YzA2YmQ5NGQ4OTNlZTM2YmYxN2RjMzFmOGUzZjFmZDE3MDM5NjY1NGNkMTBlMzYxMDgwYTE1MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCQipzi_7xlf5Lyh2mJPZrUGX-aTa90Bua_GBN509e8)

Got it! Thank you for your enthusiastic, prompt, and detailed response. wish you happiness every day.
